# specify the version key of circleci
version: 2.1

# use orb which contains a set of prepackaged circleci configs we can use to install node.js and package managers
# we use the latest version here
orbs:
  node: circleci/node@5.0.3

# create jobs: Build and test the app
jobs:
  build_and_test:
    executor: node/default 
    steps:
      - checkout
      - run: ls -l
      - node/install-packages:
        - pkg-manager: npm

# Create a workflow
workflows:
  build_test:
    jobs:
      - build_and_test:
        filters:
          branches:
            only: main