# specify the version key of circleci
version: 2.1

# use orb which contains a set of prepackaged circleci configs we can use to install node.js and package managers
# we use the latest version here
orbs:
  node: circleci/node@5.0.3

# create jobs: Build and test the app
jobs:
  build_frontend:
    working_directory: /home/circleci/project/frontend
    executor: node/default 
    steps:
      - checkout
      - run: ls -l /home/circleci/project/frontend/frontend
      - node/install-packages:
        app-dir: /home/circleci/project/frontend

# Create a workflow
workflows:
  build_frontend:
    jobs:
      - build_frontend:
        filters:
          branches:
            only: main