# specify the version key of circleci
version: 2.1

# use orb which contains a set of prepackaged circleci configs we can use to install node.js and package managers
# we use the latest version here
orbs:
  node: circleci/node@5.0.3
  docker: circleci/docker@2.1.4

# create jobs: Build and test the app
jobs:
  build_frontend:
    executor: node/default
    working_directory: ~/project/frontend
    docker:
      - image: cimg/node:lts
    steps:
      - checkout:
          path: ~/project
      - node/install-packages
      - run: npm run test
      - setup_remote_docker
      - docker/check
      - docker/build:
          image: tinyu221/repository
          tag: frontend-v1
      - docker/push:
          image: tinyu221/repository
          tag: frontend-v1
      - add_ssh_keys:
          fingerprints:
            - "99:14:c2:ce:7e:f9:13:84:11:41:7e:72:bb:f6:b7:8a"
      - run: ssh root@125.59.217.57 -p 2443 -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" "docker ps"


# Create a workflow
workflows:
  build_frontend:
    jobs:
      - build_frontend:
        filters:
          branches:
            only: main