# specify the version key of circleci
version: 2.1

# use orb which contains a set of prepackaged circleci configs we can use to install node.js and package managers
# we use the latest version here
orbs:
  node: circleci/node@5.0.3
  docker: circleci/docker@2.1.4

# create jobs: Build and test the app
jobs:
  build_frontend:
    executor: node/default
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - run: npm ci
      - docker/check
      - docker/build:
          image: tinyu221/repository:my-first-docker-image-with-circleci

# Create a workflow
workflows:
  build_frontend:
    jobs:
      - build_frontend:
        filters:
          branches:
            only: main